In [ ]:
# 1. Install system dependencies and python packages for GRIB processing
!apt-get install libeccodes-dev -qq
!pip install cfgrib -q

print("\nInstallation complete. IMPORTANT: Please go to 'Runtime' -> 'Restart session' for changes to take effect.")

Selecting previously unselected package libeccodes-data.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libeccodes-data_2.24.2-1_all.deb ...
Unpacking libeccodes-data (2.24.2-1) ...
Selecting previously unselected package libeccodes0:amd64.
Preparing to unpack .../libeccodes0_2.24.2-1_amd64.deb ...
Unpacking libeccodes0:amd64 (2.24.2-1) ...
Selecting previously unselected package libeccodes-dev:amd64.
Preparing to unpack .../libeccodes-dev_2.24.2-1_amd64.deb ...
Unpacking libeccodes-dev:amd64 (2.24.2-1) ...
Setting up libeccodes-data (2.24.2-1) ...
Setting up libeccodes0:amd64 (2.24.2-1) ...
Setting up libeccodes-dev:amd64 (2.24.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.6/91.6 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 78.3 MB/s eta 0:00:00

Installation complete. IMPORTANT: Please go to 'Runtime' -> 'Restart session' for changes to take effect.

In [ ]:
#Mounting a new folder from google colab onto drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

This section has informatoin about how to download pressure level variables
and format it

In [ ]:
print('Installing cdsapi...')
!pip install cdsapi -q
print('cdsapi installed successfully!')

import os
from google.colab import userdata

# Retrieve CDS API credentials from Colab secrets

CDSAPI_KEY = userdata.get('CDSAPI_KEY')

if CDSAPI_KEY:
    # Create the .cdsapirc file
    with open(os.path.expanduser('~/.cdsapirc'), 'w') as f:
        f.write(f'url: https://cds.climate.copernicus.eu/api')
        f.write(f'key: {CDSAPI_KEY}\n')
    print('CDS API credentials configured.')
else:
    print('Error: CDSAPI_KEY not found in Colab secrets. Please set it up as instructed.')

Installing cdsapi...
cdsapi installed successfully!
CDS API credentials configured.

In [ ]:
import pandas as pd
import os
from datetime import datetime

# --- 0. PATH CONFIGURATION ---
INPUT_CSV = '/content/drive/MyDrive/Shared_data/merged_with_terrain_dataset.csv'
OUTPUT_BASE_DIR = '/content/drive/MyDrive/Pyrocb_data/ERA5_Pressure_Levels'
FINAL_MERGED_CSV = '/content/drive/MyDrive/Pyrocb_data/merged_with_era5_pressure_final.csv'

# 1. Load the input data
df_input = pd.read_csv(INPUT_CSV)

# --- 2. CONFIGURABLE: TARGET IDs ---
# Specify IDs in this list, or set to None to process all rows
TARGET_IDS = ['179','180', '181', '189', '190', '202', '216', '253', '258', '260']

if TARGET_IDS:
    df_to_process = df_input[df_input['pyroCb_id'].astype(str).isin([str(i) for i in TARGET_IDS])].copy()
else:
    df_to_process = df_input.copy()

print(f"Found {len(df_to_process)} specific rows/hours to process for IDs: {TARGET_IDS if TARGET_IDS else 'ALL'}")
display(df_to_process[['pyroCb_id', 'time', 'pixel_latitude', 'pixel_longitude']].head())

Found 227 specific rows/hours to process for IDs: ['179', '180', '181', '189', '190', '202', '216', '253', '258', '260']

   pyroCb_id             time  pixel_latitude  pixel_longitude
0        179   5/27/2021 6:00       33.287442      -108.588483
1        179  5/27/2021 12:00       33.287442      -108.588483
2        179  5/27/2021 18:00       33.287442      -108.588483
3        179   5/28/2021 0:00       33.287442      -108.588483
4        179   5/28/2021 6:00       33.287442      -108.588483

In [ ]:
import cdsapi
import xarray as xr
import math
import numpy as np
import zipfile
import tempfile
import os
import pandas as pd # Ensure pandas is imported as it's used for isna() and to_datetime
from google.colab import userdata

# Initialize CDS Client
CDSAPI_KEY = userdata.get('CDSAPI_KEY')
c = cdsapi.Client(url='https://cds.climate.copernicus.eu/api', key=CDSAPI_KEY)

def open_era5_file(file_path):
    """Helper to open GRIB file, handling ZIP archives if necessary."""
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return None

    if zipfile.is_zipfile(file_path):
        print(f"Detected ZIP archive: {file_path}. Extracting...")
        tmpdir = tempfile.mkdtemp()
        with zipfile.ZipFile(file_path, 'r') as zip_ref:
            zip_ref.extractall(tmpdir)

        extracted = [os.path.join(tmpdir, f) for f in os.listdir(tmpdir) if f.endswith(('.grib', '.grb'))]
        if extracted:
            # Opening using the cfgrib engine explicitly
            datasets = [xr.open_dataset(f, engine='cfgrib') for f in extracted]
            return xr.merge(datasets) if len(datasets) > 1 else datasets[0]
    else:
        return xr.open_dataset(file_path, engine='cfgrib')

def process_era5_pressure_levels(row):
    pyro_id = str(row['pyroCb_id'])
    ts = pd.to_datetime(row['time'])
    date_str = ts.strftime('%Y-%m-%d')
    hour = ts.hour

    lat = row['pixel_latitude']
    lon = row['pixel_longitude']

    # --- NEW: Handle NaN latitudes/longitudes ---
    if pd.isna(lat) or pd.isna(lon):
        print(f"[WARNING] Skipping pyroCb_id {pyro_id} at {ts} due to NaN latitude or longitude.")
        return None
    # --- END NEW ---

    # Setup Directory Structure
    event_dir = os.path.join(OUTPUT_BASE_DIR, pyro_id)
    os.makedirs(event_dir, exist_ok=True)
    grib_path = os.path.join(event_dir, f"ERA5_PL_{pyro_id}_{date_str}_{hour:02d}UTC.grib")

    # Area selection
    delta_lat = 100 / 111.0
    delta_lon = 100 / (111.0 * math.cos(math.radians(lat)))
    area = [
        round((lat + delta_lat)*4)/4, round((lon - delta_lon)*4)/4,
        round((lat - delta_lat)*4)/4, round((lon + delta_lon)*4)/4
    ]

    # Download
    if not os.path.exists(grib_path):
        print(f"[LOG] Downloading PL data for ID {pyro_id} at {ts}...")
        try:
            c.retrieve('reanalysis-era5-pressure-levels', {
                'product_type': 'reanalysis',
                'format': 'grib',
                'variable': ['relative_humidity', 'u_component_of_wind', 'v_component_of_wind'],
                'pressure_level': ['250', '650', '750', '850'],
                'year': str(ts.year),
                'month': f"{ts.month:02d}",
                'day': f"{ts.day:02d}",
                'time': f"{hour:02d}:00",
                'area': area,
            }, grib_path)
        except Exception as e:
            print(f"[ERROR] Download failed for {pyro_id} at {ts}: {e}")
            return None

    # Extract point data using the ZIP-aware helper
    try:
        ds = open_era5_file(grib_path)
        if ds is None: return None

        point = ds.sel(latitude=lat, longitude=lon, method='nearest')

        res = {
            'pyroCb_id': row['pyroCb_id'],
            'time': row['time'],
            'pixel_latitude': row['pixel_latitude'],
            'pixel_longitude': row['pixel_longitude'],
            'rh_650': point.sel(isobaricInhPa=650).r.values.item(),
            'rh_750': point.sel(isobaricInhPa=750).r.values.item(),
            'rh_850': point.sel(isobaricInhPa=850).r.values.item(),
            'u_250': point.sel(isobaricInhPa=250).u.values.item(),
            'v_250': point.sel(isobaricInhPa=250).v.values.item()
        }
        ds.close()
        return res
    except Exception as e:
        print(f"[ERROR] Extraction failed for {pyro_id} at {ts}: {e}")
        return None

# Execute Batch
results_list = []
for index, row in df_to_process.iterrows():
    extracted = process_era5_pressure_levels(row)
    if extracted:
        results_list.append(extracted)

df_era5_new = pd.DataFrame(results_list)
print(f"Extraction complete for {len(df_era5_new)} rows.")

[WARNING] Skipping pyroCb_id 189 at 2021-06-29 19:00:00 due to NaN latitude or longitude.
[LOG] Downloading PL data for ID 189 at 2021-06-30 01:00:00...

2026-07-30 04:08:37,205 INFO Request ID is 87636785-a692-4ee5-b905-1c76dcbcdd3e
INFO:ecmwf.datastores.legacy_client:Request ID is 87636785-a692-4ee5-b905-1c76dcbcdd3e
2026-07-30 04:08:37,946 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:09:00,256 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:09:11,797 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9a22b90ba0106817c489c3b5ba651efe.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-06-30 07:00:00...

2026-07-30 04:09:13,518 INFO Request ID is 176829e8-40b2-4324-8c52-20e7f9450101
INFO:ecmwf.datastores.legacy_client:Request ID is 176829e8-40b2-4324-8c52-20e7f9450101
2026-07-30 04:09:13,665 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:09:47,935 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

755d9952aea8a012405ee15521248748.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-06-30 13:00:00...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-07-30 04:11:50,479 INFO Request ID is 9689ed99-f6e3-4abe-a8de-314cdf6f6945
INFO:ecmwf.datastores.legacy_client:Request ID is 9689ed99-f6e3-4abe-a8de-314cdf6f6945
2026-07-30 04:11:51,006 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:12:26,689 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

19d5f4baf6c9a780155dcac6bd8ab01c.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-06-30 19:00:00...

2026-07-30 04:12:29,621 INFO Request ID is 04ed448c-23a8-49bb-be70-27870c3e7226
INFO:ecmwf.datastores.legacy_client:Request ID is 04ed448c-23a8-49bb-be70-27870c3e7226
2026-07-30 04:12:29,754 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:12:51,545 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d14b3b772635dfdef8af62e8a4bd3ac8.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-01 01:00:00...

2026-07-30 04:12:53,102 INFO Request ID is 836eb9b6-f18d-49d7-9b60-9bbc591f5963
INFO:ecmwf.datastores.legacy_client:Request ID is 836eb9b6-f18d-49d7-9b60-9bbc591f5963
2026-07-30 04:12:53,249 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:13:26,384 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1607fd5e11cefaa84637f274a5c0a6b8.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-01 07:00:00...

2026-07-30 04:13:28,004 INFO Request ID is f0336526-8859-4104-9127-026c8639dd83
INFO:ecmwf.datastores.legacy_client:Request ID is f0336526-8859-4104-9127-026c8639dd83
2026-07-30 04:13:28,155 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:13:49,803 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:14:01,327 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

98b4233e50e8a34bb23914449c137e74.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-01 13:00:00...

2026-07-30 04:14:04,509 INFO Request ID is 2715c6cb-713d-415d-a2dd-847037c339b0
INFO:ecmwf.datastores.legacy_client:Request ID is 2715c6cb-713d-415d-a2dd-847037c339b0
2026-07-30 04:14:04,676 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:14:40,211 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

df028f5663b2dd96866cf5ac86f765f3.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-01 19:00:00...

2026-07-30 04:14:42,419 INFO Request ID is 40a7d71d-243a-47cf-861e-c8523b3353e0
INFO:ecmwf.datastores.legacy_client:Request ID is 40a7d71d-243a-47cf-861e-c8523b3353e0
2026-07-30 04:14:42,554 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:14:59,926 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:15:07,699 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e02600058c3be8f77a095372839efcf5.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-02 01:00:00...

2026-07-30 04:15:09,348 INFO Request ID is a08b3133-a309-47b1-addc-775d04de9c79
INFO:ecmwf.datastores.legacy_client:Request ID is a08b3133-a309-47b1-addc-775d04de9c79
2026-07-30 04:15:09,507 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:15:32,187 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ccf433fe0b8dbd7d300499cabc7e2b36.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-02 07:00:00...

2026-07-30 04:15:34,001 INFO Request ID is c56865ef-e54f-4741-ae91-1f2711390280
INFO:ecmwf.datastores.legacy_client:Request ID is c56865ef-e54f-4741-ae91-1f2711390280
2026-07-30 04:15:34,138 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:16:07,270 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

84f22dce7376bcfa087882bd043af070.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-02 13:00:00...

2026-07-30 04:16:10,535 INFO Request ID is 984002bc-a276-4f53-85c8-5afc041b61a0
INFO:ecmwf.datastores.legacy_client:Request ID is 984002bc-a276-4f53-85c8-5afc041b61a0
2026-07-30 04:16:10,685 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:16:32,825 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4e9cf5cbce36f9ecd0e1469fba049974.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-02 19:00:00...

2026-07-30 04:16:34,674 INFO Request ID is f309a9d8-eeaa-4756-a536-73275c2238fd
INFO:ecmwf.datastores.legacy_client:Request ID is f309a9d8-eeaa-4756-a536-73275c2238fd
2026-07-30 04:16:34,826 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:16:57,518 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:17:09,069 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b438bf19bde43b6807c709c530804d2a.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-03 01:00:00...

2026-07-30 04:17:12,199 INFO Request ID is 3ff85534-fbd9-4ec6-ab2c-e21bb84755f1
INFO:ecmwf.datastores.legacy_client:Request ID is 3ff85534-fbd9-4ec6-ab2c-e21bb84755f1
2026-07-30 04:17:13,801 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:17:46,991 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

62d2fb81590d552e49e81c4e26428b3b.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-03 07:00:00...

2026-07-30 04:17:48,546 INFO Request ID is cf49b0bb-8499-4291-9cc2-fe2163f650a0
INFO:ecmwf.datastores.legacy_client:Request ID is cf49b0bb-8499-4291-9cc2-fe2163f650a0
2026-07-30 04:17:48,707 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:18:11,892 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b992ac3323d861b93bf918883007bf91.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-03 13:00:00...

2026-07-30 04:18:16,044 INFO Request ID is 3ac807b8-2945-4395-998b-e310dbeafacc
INFO:ecmwf.datastores.legacy_client:Request ID is 3ac807b8-2945-4395-998b-e310dbeafacc
2026-07-30 04:18:16,175 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:18:33,619 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:18:41,350 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

27307c4d7369222d9269d784aeb381ee.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 189 at 2021-07-03 19:00:00...

2026-07-30 04:18:43,008 INFO Request ID is 5e506d31-bcf2-4e3e-9609-32364982a86b
INFO:ecmwf.datastores.legacy_client:Request ID is 5e506d31-bcf2-4e3e-9609-32364982a86b
2026-07-30 04:18:43,161 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:19:05,019 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8ea31239f215335e5a3049df2bca27f1.grib:   0%|          | 0.00/3.14k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-28 07:00:00...

2026-07-30 04:19:06,745 INFO Request ID is 748082d5-e7a4-4a30-ade3-41496131ce67
INFO:ecmwf.datastores.legacy_client:Request ID is 748082d5-e7a4-4a30-ade3-41496131ce67
2026-07-30 04:19:06,879 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:19:30,224 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:19:41,899 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

886d52527f2dff86ffe900306660b7ad.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-28 13:00:00...

2026-07-30 04:19:43,620 INFO Request ID is 99bc15a8-d823-4f03-833b-1d2f236009b9
INFO:ecmwf.datastores.legacy_client:Request ID is 99bc15a8-d823-4f03-833b-1d2f236009b9
2026-07-30 04:19:43,753 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:20:18,393 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7c3de7d385327fbba984b4f226a574f.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-28 19:00:00...

2026-07-30 04:20:20,118 INFO Request ID is 5cf037b5-0229-4ea6-ba5e-d73a47db565b
INFO:ecmwf.datastores.legacy_client:Request ID is 5cf037b5-0229-4ea6-ba5e-d73a47db565b
2026-07-30 04:20:20,257 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:20:41,835 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:20:53,370 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1de9b3cf2825033ff8bf1180ae3affb9.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-29 01:00:00...

2026-07-30 04:20:55,042 INFO Request ID is 65fd426c-5e8a-4f23-8248-66e5b0b487e7
INFO:ecmwf.datastores.legacy_client:Request ID is 65fd426c-5e8a-4f23-8248-66e5b0b487e7
2026-07-30 04:20:55,205 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:21:28,535 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e48572b854aaaa41984447cbabf6b26e.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-29 07:00:00...

2026-07-30 04:21:30,170 INFO Request ID is c12b0fdc-c7a8-4b43-806a-829d37458723
INFO:ecmwf.datastores.legacy_client:Request ID is c12b0fdc-c7a8-4b43-806a-829d37458723
2026-07-30 04:21:30,333 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:21:47,384 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:22:06,732 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8e7786192fe543de54bc743a64eb8a6c.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[WARNING] Skipping pyroCb_id 190 at 2021-06-29 19:00:00 due to NaN latitude or longitude.
[LOG] Downloading PL data for ID 190 at 2021-06-30 01:00:00...

2026-07-30 04:22:08,462 INFO Request ID is e4360e58-648d-455c-8ccc-44ca535ff4cb
INFO:ecmwf.datastores.legacy_client:Request ID is e4360e58-648d-455c-8ccc-44ca535ff4cb
2026-07-30 04:22:08,761 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:22:30,714 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:22:42,420 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d1b210d248b41fec9080178bf4d08903.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-30 07:00:00...

2026-07-30 04:22:44,230 INFO Request ID is 8924f295-dd9e-4e1d-9f11-98affcc436e1
INFO:ecmwf.datastores.legacy_client:Request ID is 8924f295-dd9e-4e1d-9f11-98affcc436e1
2026-07-30 04:22:44,362 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:23:18,708 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:23:35,927 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d04e6d3d1839fe152a01150ecbbf0f93.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-30 13:00:00...

2026-07-30 04:23:37,690 INFO Request ID is a741315c-b546-4468-aea9-f85abf6f004b
INFO:ecmwf.datastores.legacy_client:Request ID is a741315c-b546-4468-aea9-f85abf6f004b
2026-07-30 04:23:37,841 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:23:59,610 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:24:11,549 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

14b26ad499296031e8616aba18bee01.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-06-30 19:00:00...

2026-07-30 04:24:13,153 INFO Request ID is a462761a-d06e-448e-a384-cdfa055994d4
INFO:ecmwf.datastores.legacy_client:Request ID is a462761a-d06e-448e-a384-cdfa055994d4
2026-07-30 04:24:13,290 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:24:49,747 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3e0be2f7e5b37fb3807b5d3f330d3871.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-01 01:00:00...

2026-07-30 04:24:51,364 INFO Request ID is 89039f12-a087-4a23-b173-09b1f0091f9d
INFO:ecmwf.datastores.legacy_client:Request ID is 89039f12-a087-4a23-b173-09b1f0091f9d
2026-07-30 04:24:51,517 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:25:24,837 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4df027c78bd6b2bf60cbb271830f6e84.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-01 07:00:00...

2026-07-30 04:25:27,451 INFO Request ID is 94b1b9db-4a8f-4738-a184-8b79639d2fe9
INFO:ecmwf.datastores.legacy_client:Request ID is 94b1b9db-4a8f-4738-a184-8b79639d2fe9
2026-07-30 04:25:27,585 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:25:50,469 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fc5b63d8a3264ee4a9ac07cc9ab17078.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-01 13:00:00...

2026-07-30 04:26:01,258 INFO Request ID is 363f59ea-0501-4baa-adfa-d47a419745d2
INFO:ecmwf.datastores.legacy_client:Request ID is 363f59ea-0501-4baa-adfa-d47a419745d2
2026-07-30 04:26:01,782 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:26:26,220 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:26:37,750 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

70bc8017ec353f2eccec128bf54964c9.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-01 19:00:00...

2026-07-30 04:26:39,403 INFO Request ID is 34d2925f-8ea1-4350-8223-9025b0667d3d
INFO:ecmwf.datastores.legacy_client:Request ID is 34d2925f-8ea1-4350-8223-9025b0667d3d
2026-07-30 04:26:39,549 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:27:57,522 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

58ed148ffaec4e21fa1cc7b157bdb7fc.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-02 01:00:00...

2026-07-30 04:27:59,605 INFO Request ID is 03a34a35-a69b-4d28-86d1-874557c41412
INFO:ecmwf.datastores.legacy_client:Request ID is 03a34a35-a69b-4d28-86d1-874557c41412
2026-07-30 04:27:59,750 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:28:21,693 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:28:33,217 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8077092582a9dd163a459fd843341918.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-02 07:00:00...

2026-07-30 04:28:34,990 INFO Request ID is 735d40f7-3ddc-4209-91e2-63f5a1545f92
INFO:ecmwf.datastores.legacy_client:Request ID is 735d40f7-3ddc-4209-91e2-63f5a1545f92
2026-07-30 04:28:35,165 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:28:56,765 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:29:09,520 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

928aabaccd31229aaf0163ec8ba1d680.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-02 13:00:00...

2026-07-30 04:29:14,771 INFO Request ID is 03f0396d-490b-46e4-961c-7df1884939e1
INFO:ecmwf.datastores.legacy_client:Request ID is 03f0396d-490b-46e4-961c-7df1884939e1
2026-07-30 04:29:14,986 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:29:36,664 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:29:48,191 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4b30b642743c67b36e4db22d41792974.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-02 19:00:00...

2026-07-30 04:29:51,208 INFO Request ID is 13757512-bb44-4d58-ba0f-50795e80173e
INFO:ecmwf.datastores.legacy_client:Request ID is 13757512-bb44-4d58-ba0f-50795e80173e
2026-07-30 04:29:51,338 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:30:12,980 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f1c5e1b81cd981d60908f47957919c2a.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-03 01:00:00...

2026-07-30 04:30:14,468 INFO Request ID is a3fd882b-a13d-4931-b914-0c5db26b1286
INFO:ecmwf.datastores.legacy_client:Request ID is a3fd882b-a13d-4931-b914-0c5db26b1286
2026-07-30 04:30:14,649 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:30:36,302 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:31:30,847 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a4140b65802c8d15c7b71276e6762b90.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-03 07:00:00...

2026-07-30 04:31:33,494 INFO Request ID is b05b9df4-9cf4-4843-a05c-fac1db5977ef
INFO:ecmwf.datastores.legacy_client:Request ID is b05b9df4-9cf4-4843-a05c-fac1db5977ef
2026-07-30 04:31:33,651 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:31:55,442 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:32:07,156 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d19464f6e243566ea27009cec844d97.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-03 13:00:00...

2026-07-30 04:32:09,238 INFO Request ID is 5b779324-f917-4237-bb94-617dc4a002bd
INFO:ecmwf.datastores.legacy_client:Request ID is 5b779324-f917-4237-bb94-617dc4a002bd
2026-07-30 04:32:09,385 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:32:31,024 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:32:42,830 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2e7381d1fd783315fcc54c60bc849724.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 190 at 2021-07-03 19:00:00...

2026-07-30 04:32:44,861 INFO Request ID is 364f212c-4972-41a9-a3b6-118afe49acaa
INFO:ecmwf.datastores.legacy_client:Request ID is 364f212c-4972-41a9-a3b6-118afe49acaa
2026-07-30 04:32:45,005 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:33:08,520 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:33:20,041 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

784f199e5ae69fe2aef58cad31cb0652.grib:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-08 05:00:00...

2026-07-30 04:33:21,758 INFO Request ID is 10a40e0f-3a6c-4a5f-8d8b-e0b29dee922b
INFO:ecmwf.datastores.legacy_client:Request ID is 10a40e0f-3a6c-4a5f-8d8b-e0b29dee922b
2026-07-30 04:33:22,186 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:33:55,649 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8f29bdb13b544368ad12c5f4338f34f3.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-08 11:00:00...

2026-07-30 04:33:57,294 INFO Request ID is 2323a969-b61b-49d9-b4ca-ee09512c9c07
INFO:ecmwf.datastores.legacy_client:Request ID is 2323a969-b61b-49d9-b4ca-ee09512c9c07
2026-07-30 04:33:57,699 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:34:30,918 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:34:48,137 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

113c6f9e95b2075e92227b38d24d548f.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-08 17:00:00...

2026-07-30 04:34:49,841 INFO Request ID is 53c39c82-9d81-4ed3-9f4d-618d9f289755
INFO:ecmwf.datastores.legacy_client:Request ID is 53c39c82-9d81-4ed3-9f4d-618d9f289755
2026-07-30 04:34:49,999 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:35:04,002 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:35:11,730 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

62d0839d46ebfe597507f8d6155000a3.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-08 23:00:00...

2026-07-30 04:35:13,308 INFO Request ID is 621454a6-d0aa-4e4e-93b5-e5f95454ffc4
INFO:ecmwf.datastores.legacy_client:Request ID is 621454a6-d0aa-4e4e-93b5-e5f95454ffc4
2026-07-30 04:35:13,457 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:35:27,675 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:35:36,130 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5a3f524f0bd75b2b39058930e99cbcd2.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-09 05:00:00...

2026-07-30 04:35:37,790 INFO Request ID is 194a96a2-e061-4495-9468-16b2641645c3
INFO:ecmwf.datastores.legacy_client:Request ID is 194a96a2-e061-4495-9468-16b2641645c3
2026-07-30 04:35:38,377 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:36:02,673 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

232b0c97405321ec98650c66352ea4e5.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-09 17:00:00...

2026-07-30 04:36:04,222 INFO Request ID is d870c93e-71ce-4421-93cc-bd474e454e73
INFO:ecmwf.datastores.legacy_client:Request ID is d870c93e-71ce-4421-93cc-bd474e454e73
2026-07-30 04:36:04,359 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:36:26,125 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:36:37,692 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ee9101d52231c00df3717a56accf7bff.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-09 23:00:00...

2026-07-30 04:36:42,981 INFO Request ID is 428c3c37-e9a7-4ea7-9d49-542c27ef1082
INFO:ecmwf.datastores.legacy_client:Request ID is 428c3c37-e9a7-4ea7-9d49-542c27ef1082
2026-07-30 04:36:43,130 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:37:04,702 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

10d7296ed29f2afe4ec7965657347b8c.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-10 05:00:00...

2026-07-30 04:37:06,284 INFO Request ID is 89c667ae-52d8-44d6-8df7-ad41609ed325
INFO:ecmwf.datastores.legacy_client:Request ID is 89c667ae-52d8-44d6-8df7-ad41609ed325
2026-07-30 04:37:06,437 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:37:28,000 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:37:39,524 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a4967a70a32df9a36c5cbffabf254852.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-10 11:00:00...

2026-07-30 04:37:42,919 INFO Request ID is 4101ce98-5cac-434a-9aca-4d63c014e324
INFO:ecmwf.datastores.legacy_client:Request ID is 4101ce98-5cac-434a-9aca-4d63c014e324
2026-07-30 04:37:43,054 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:38:04,673 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b3f04abd67319a1f5f6a5e4bc5372c6.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-10 17:00:00...

2026-07-30 04:38:06,206 INFO Request ID is 31fd5fdf-e1fd-414e-9cea-7b5d3d28f1c7
INFO:ecmwf.datastores.legacy_client:Request ID is 31fd5fdf-e1fd-414e-9cea-7b5d3d28f1c7
2026-07-30 04:38:06,345 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:38:27,960 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:38:39,514 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

867dda0fd7c3832be888b2254a8dfc9f.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-10 23:00:00...

2026-07-30 04:38:41,562 INFO Request ID is 6e749cd7-7b6c-4afe-b846-5e2c23b872ee
INFO:ecmwf.datastores.legacy_client:Request ID is 6e749cd7-7b6c-4afe-b846-5e2c23b872ee
2026-07-30 04:38:41,709 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:39:03,370 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:39:14,906 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

57614d9ccda968576d040f9f279f74a5.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-11 05:00:00...

2026-07-30 04:39:17,262 INFO Request ID is e7b5657d-3e71-46e9-a52f-31ddeab5e51f
INFO:ecmwf.datastores.legacy_client:Request ID is e7b5657d-3e71-46e9-a52f-31ddeab5e51f
2026-07-30 04:39:17,403 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:39:39,057 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:39:50,582 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ac44bfaa4c18e8fe67b87375b95c793b.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-11 11:00:00...

2026-07-30 04:39:52,162 INFO Request ID is 6f8d1cf9-cc7c-4f8f-861d-100a7be00392
INFO:ecmwf.datastores.legacy_client:Request ID is 6f8d1cf9-cc7c-4f8f-861d-100a7be00392
2026-07-30 04:39:52,311 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:40:14,174 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3400615df5018b3f9a71afa7d1c8845e.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-11 17:00:00...

2026-07-30 04:40:16,505 INFO Request ID is d9a3eada-7628-43f7-b4d1-26b456fca609
INFO:ecmwf.datastores.legacy_client:Request ID is d9a3eada-7628-43f7-b4d1-26b456fca609
2026-07-30 04:40:16,642 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:40:32,133 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:40:39,863 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cbf2ed190d6035ef8b1635a8b56abb28.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-11 23:00:00...

2026-07-30 04:40:41,557 INFO Request ID is 9bd697b1-77ec-40ba-be68-23302ab98085
INFO:ecmwf.datastores.legacy_client:Request ID is 9bd697b1-77ec-40ba-be68-23302ab98085
2026-07-30 04:40:41,713 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:41:03,561 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:41:15,087 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

87bf9665e9116065c48135ad776ff81a.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-12 05:00:00...

2026-07-30 04:41:16,887 INFO Request ID is 5b057f3c-5f85-474f-9353-f8d7ed344e2f
INFO:ecmwf.datastores.legacy_client:Request ID is 5b057f3c-5f85-474f-9353-f8d7ed344e2f
2026-07-30 04:41:17,170 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:41:38,779 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

28fa404e6af676328f32cf9c91a18c6d.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-12 11:00:00...

2026-07-30 04:41:40,314 INFO Request ID is 4df8f018-ec77-430e-a75e-83317cd9c366
INFO:ecmwf.datastores.legacy_client:Request ID is 4df8f018-ec77-430e-a75e-83317cd9c366
2026-07-30 04:41:40,472 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:42:03,408 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

237143a189cfdea4e4e708cc61e8ec2d.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-12 17:00:00...

2026-07-30 04:42:05,085 INFO Request ID is 72afdfd4-5364-402c-856d-1ff836bbfa0a
INFO:ecmwf.datastores.legacy_client:Request ID is 72afdfd4-5364-402c-856d-1ff836bbfa0a
2026-07-30 04:42:05,216 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:42:19,858 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:42:27,655 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

70e25459930b08db703dd9709b0c813.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-12 23:00:00...

2026-07-30 04:42:31,434 INFO Request ID is e1605e97-323e-4455-9e7d-a0c89de5620a
INFO:ecmwf.datastores.legacy_client:Request ID is e1605e97-323e-4455-9e7d-a0c89de5620a
2026-07-30 04:42:32,575 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:42:56,764 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:43:08,306 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

127398879fa8519dddc2db809b8d1f3.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-13 05:00:00...

2026-07-30 04:43:10,612 INFO Request ID is 9edc8ea9-fd10-4bea-9a00-1c2d0c6385b4
INFO:ecmwf.datastores.legacy_client:Request ID is 9edc8ea9-fd10-4bea-9a00-1c2d0c6385b4
2026-07-30 04:43:10,758 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:43:32,558 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:43:44,083 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

341d36a0cad0c362470e5e33ba862c4c.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-13 11:00:00...

2026-07-30 04:43:45,861 INFO Request ID is cee81d0c-1275-4f43-9108-4248b7b9439a
INFO:ecmwf.datastores.legacy_client:Request ID is cee81d0c-1275-4f43-9108-4248b7b9439a
2026-07-30 04:43:46,019 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:44:08,430 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2e6c63521fc9a89f464b3e96ce9919a5.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-13 17:00:00...

2026-07-30 04:44:09,986 INFO Request ID is b34a6788-4fb1-4dd9-9e45-c4a93b5fcbcb
INFO:ecmwf.datastores.legacy_client:Request ID is b34a6788-4fb1-4dd9-9e45-c4a93b5fcbcb
2026-07-30 04:44:10,208 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:44:32,776 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7e35a8928ce79cd00231e28871354ac5.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 202 at 2021-07-13 23:00:00...

2026-07-30 04:44:34,500 INFO Request ID is 53c73e85-df48-47a2-b58f-72acd60204b8
INFO:ecmwf.datastores.legacy_client:Request ID is 53c73e85-df48-47a2-b58f-72acd60204b8
2026-07-30 04:44:34,657 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:44:57,614 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8b23478ebe7c758774c04df27ab8fc31.grib:   0%|          | 0.00/3.70k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-17 07:00:00...

2026-07-30 04:44:59,151 INFO Request ID is 90e25924-a526-4b4b-b6c5-7b0aa334d5b7
INFO:ecmwf.datastores.legacy_client:Request ID is 90e25924-a526-4b4b-b6c5-7b0aa334d5b7
2026-07-30 04:44:59,294 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:45:21,490 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:45:33,015 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b55934a4cdf9b70d75ebe5f0139bf8d4.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-17 13:00:00...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-07-30 04:47:39,671 INFO Request ID is 0d6c3205-f6d5-41ad-aa0d-b20ab7330300
INFO:ecmwf.datastores.legacy_client:Request ID is 0d6c3205-f6d5-41ad-aa0d-b20ab7330300
2026-07-30 04:47:39,818 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:48:03,115 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:48:15,017 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cf17cdafe34a45bb7a4a60ded86629df.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-17 19:00:00...

2026-07-30 04:48:17,608 INFO Request ID is 9d2a4ad5-4b42-4632-9462-0f94d0d58de6
INFO:ecmwf.datastores.legacy_client:Request ID is 9d2a4ad5-4b42-4632-9462-0f94d0d58de6
2026-07-30 04:48:17,739 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:48:41,371 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fc58df8f2aaa6d76f08a082fd9d2aaf6.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-18 01:00:00...

2026-07-30 04:48:48,507 INFO Request ID is d0b1935c-ced6-4419-ad62-1338e9d01391
INFO:ecmwf.datastores.legacy_client:Request ID is d0b1935c-ced6-4419-ad62-1338e9d01391
2026-07-30 04:48:49,082 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:49:14,079 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:49:25,615 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d0e59750902225372b3e33db62e5e72e.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-18 07:00:00...

2026-07-30 04:49:27,281 INFO Request ID is 34f05e51-4a8c-4eea-ac11-5c32a6ec91e5
INFO:ecmwf.datastores.legacy_client:Request ID is 34f05e51-4a8c-4eea-ac11-5c32a6ec91e5
2026-07-30 04:49:29,556 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:50:20,113 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b14111c3c67e9a8c4939fbf37214bdfb.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-18 13:00:00...

2026-07-30 04:50:22,653 INFO Request ID is 5ed81f40-f6e0-4e02-b308-89b4aa10c725
INFO:ecmwf.datastores.legacy_client:Request ID is 5ed81f40-f6e0-4e02-b308-89b4aa10c725
2026-07-30 04:50:22,782 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:50:56,714 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1efd42f77cf283308af2efc80f297bf1.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-18 19:00:00...

2026-07-30 04:51:00,151 INFO Request ID is 9212dea8-9210-4dce-82b8-f5573b7566af
INFO:ecmwf.datastores.legacy_client:Request ID is 9212dea8-9210-4dce-82b8-f5573b7566af
2026-07-30 04:51:00,302 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:51:21,945 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:51:33,474 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

52ade5fd885574b6d0e5805c0c0d5f9f.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-19 01:00:00...

2026-07-30 04:51:35,247 INFO Request ID is e179dcec-e494-4b9e-a51c-26ad09fabeb8
INFO:ecmwf.datastores.legacy_client:Request ID is e179dcec-e494-4b9e-a51c-26ad09fabeb8
2026-07-30 04:51:35,392 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:51:57,019 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

db01a2bd2b4d533b434627121aa840a4.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-19 07:00:00...

2026-07-30 04:51:58,587 INFO Request ID is b53ab84e-ff80-4bc2-b1af-2c62529f445d
INFO:ecmwf.datastores.legacy_client:Request ID is b53ab84e-ff80-4bc2-b1af-2c62529f445d
2026-07-30 04:51:58,733 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:52:15,738 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:52:25,565 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5afa9479d682d3dcbb6f28afad40d812.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-19 13:00:00...

2026-07-30 04:52:27,195 INFO Request ID is 0f396f6b-8e8e-4037-ad3a-e4d82e9992e7
INFO:ecmwf.datastores.legacy_client:Request ID is 0f396f6b-8e8e-4037-ad3a-e4d82e9992e7
2026-07-30 04:52:27,344 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:52:49,643 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:53:01,172 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f201f59b45b94b22fb7682152c0e392e.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-19 19:00:00...

2026-07-30 04:53:03,576 INFO Request ID is 853a4567-2205-46ff-8e8a-dcff889ef717
INFO:ecmwf.datastores.legacy_client:Request ID is 853a4567-2205-46ff-8e8a-dcff889ef717
2026-07-30 04:53:03,734 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:53:20,323 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:53:28,070 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

612181049fcd926ddcce3e1ec815619c.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-20 01:00:00...

2026-07-30 04:53:29,607 INFO Request ID is 71bded6d-4118-4989-898d-46d7262e4a90
INFO:ecmwf.datastores.legacy_client:Request ID is 71bded6d-4118-4989-898d-46d7262e4a90
2026-07-30 04:53:29,753 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:53:40,708 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:53:53,624 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1ff6a002aee2a9f8f9f4fdbf270919bc.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-20 07:00:00...

2026-07-30 04:53:55,288 INFO Request ID is 4379637a-92f9-4041-95ba-44ed436d449a
INFO:ecmwf.datastores.legacy_client:Request ID is 4379637a-92f9-4041-95ba-44ed436d449a
2026-07-30 04:53:55,436 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:54:17,031 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:54:46,470 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

3926292da1dc6c58d69f0f81bcee578b.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-20 13:00:00...

2026-07-30 04:54:48,243 INFO Request ID is 81e06231-7398-4941-abc8-6688df89aa6b
INFO:ecmwf.datastores.legacy_client:Request ID is 81e06231-7398-4941-abc8-6688df89aa6b
2026-07-30 04:54:48,387 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:55:04,795 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:55:12,524 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4205ac97a70408502e972dad40c65715.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-20 19:00:00...

2026-07-30 04:55:14,162 INFO Request ID is 8cdee02a-a980-46fa-9b99-35c09ede51ff
INFO:ecmwf.datastores.legacy_client:Request ID is 8cdee02a-a980-46fa-9b99-35c09ede51ff
2026-07-30 04:55:14,295 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:55:35,889 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bf4539334fa90ab3931adbd582b36f66.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-21 01:00:00...

2026-07-30 04:55:37,574 INFO Request ID is b283f875-abac-4719-a841-d4fe89cf4983
INFO:ecmwf.datastores.legacy_client:Request ID is b283f875-abac-4719-a841-d4fe89cf4983
2026-07-30 04:55:37,732 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:55:59,330 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

28dbead4593f3b16156e180bcdc41cdc.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-21 07:00:00...

2026-07-30 04:56:01,517 INFO Request ID is 72985670-dad5-427a-82de-96f65e6be834
INFO:ecmwf.datastores.legacy_client:Request ID is 72985670-dad5-427a-82de-96f65e6be834
2026-07-30 04:56:01,817 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:56:24,548 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

be904e4b1cf35ed9720a59594c95ea7f.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-21 13:00:00...

2026-07-30 04:56:26,742 INFO Request ID is 50ec777d-1ab7-4627-8d73-a1820ba8e6bc
INFO:ecmwf.datastores.legacy_client:Request ID is 50ec777d-1ab7-4627-8d73-a1820ba8e6bc
2026-07-30 04:56:26,888 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:56:40,775 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:56:48,518 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9df66a05a2723106552711f19d188d95.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 216 at 2021-07-21 19:00:00...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-07-30 04:58:50,917 INFO Request ID is 54c470da-1745-4927-9113-210107e2a838
INFO:ecmwf.datastores.legacy_client:Request ID is 54c470da-1745-4927-9113-210107e2a838
2026-07-30 04:58:51,066 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:59:12,900 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:59:24,421 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e0446e7a50fef1aa2aed13176cceed42.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-29 04:00:00...

2026-07-30 04:59:26,114 INFO Request ID is d1a01882-1055-4c66-aba5-10e5eaff282c
INFO:ecmwf.datastores.legacy_client:Request ID is d1a01882-1055-4c66-aba5-10e5eaff282c
2026-07-30 04:59:26,274 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 04:59:48,416 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 04:59:59,956 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b5885b6a7e5b0023ae67e56f15a06ba2.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-29 10:00:00...

2026-07-30 05:00:01,527 INFO Request ID is 88d9180f-a127-490a-88b2-2e302f0c6636
INFO:ecmwf.datastores.legacy_client:Request ID is 88d9180f-a127-490a-88b2-2e302f0c6636
2026-07-30 05:00:01,750 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:00:26,454 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:00:38,012 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

409fa1f5213201700562a789570c7d.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-29 16:00:00...

2026-07-30 05:00:39,796 INFO Request ID is 6c0ecebc-2bbc-4fd5-94a2-5f1bc2dca112
INFO:ecmwf.datastores.legacy_client:Request ID is 6c0ecebc-2bbc-4fd5-94a2-5f1bc2dca112
2026-07-30 05:00:39,928 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:01:04,645 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:01:16,187 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6364722de60fd62fad763f83fd6e11c8.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-29 22:00:00...

2026-07-30 05:01:17,918 INFO Request ID is ab54f76a-0582-4d24-a770-92b97e9442a3
INFO:ecmwf.datastores.legacy_client:Request ID is ab54f76a-0582-4d24-a770-92b97e9442a3
2026-07-30 05:01:18,064 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:02:34,756 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1addf71c4e99fc7148cc565aa548e357.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-30 04:00:00...

2026-07-30 05:02:36,826 INFO Request ID is 492344c1-00f5-4114-b4e2-4b757f9acb5d
INFO:ecmwf.datastores.legacy_client:Request ID is 492344c1-00f5-4114-b4e2-4b757f9acb5d
2026-07-30 05:02:36,956 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:03:00,320 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a78363abf015962aac7faad8d0cc49f6.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-30 10:00:00...

2026-07-30 05:03:01,888 INFO Request ID is 664913c6-ba6e-4530-92c1-a37c682b0156
INFO:ecmwf.datastores.legacy_client:Request ID is 664913c6-ba6e-4530-92c1-a37c682b0156
2026-07-30 05:03:02,146 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:03:52,499 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:04:18,271 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

797d815bd2e5221d9af39eaafe9c7957.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-30 16:00:00...

2026-07-30 05:04:19,928 INFO Request ID is 842b10e6-5d24-410e-aa31-5a582e0ca372
INFO:ecmwf.datastores.legacy_client:Request ID is 842b10e6-5d24-410e-aa31-5a582e0ca372
2026-07-30 05:04:20,078 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:04:34,335 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:04:42,060 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

d1eb5244c7843a2b9df7b6c3070918b2.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-30 22:00:00...

2026-07-30 05:04:44,934 INFO Request ID is aaa344e1-9e46-4d86-a495-6c2ea373e69e
INFO:ecmwf.datastores.legacy_client:Request ID is aaa344e1-9e46-4d86-a495-6c2ea373e69e
2026-07-30 05:04:45,066 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:05:08,653 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

337c2682a0147834ffe0d742a77a2ab0.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-31 04:00:00...

2026-07-30 05:05:10,104 INFO Request ID is 51ea30ab-c26c-4ad7-bae0-4db0e3359a91
INFO:ecmwf.datastores.legacy_client:Request ID is 51ea30ab-c26c-4ad7-bae0-4db0e3359a91
2026-07-30 05:05:10,232 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:05:31,868 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

82082f41e04a507e82bbf8a4e31a8947.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-31 10:00:00...

2026-07-30 05:05:36,824 INFO Request ID is 52d6a81f-d059-4b37-afbc-a3fc4712aae8
INFO:ecmwf.datastores.legacy_client:Request ID is 52d6a81f-d059-4b37-afbc-a3fc4712aae8
2026-07-30 05:05:37,862 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:05:54,953 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:06:02,682 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7f16098ce383790ecfbda225468a5df6.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-31 16:00:00...

2026-07-30 05:06:04,729 INFO Request ID is eadebef9-fd4d-438d-9fa2-b0909998bc44
INFO:ecmwf.datastores.legacy_client:Request ID is eadebef9-fd4d-438d-9fa2-b0909998bc44
2026-07-30 05:06:04,868 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:06:19,313 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:06:27,057 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ed60bd4309a0e293e073fbd6ec42ba06.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-03-31 22:00:00...

2026-07-30 05:06:28,676 INFO Request ID is 52878a9a-022d-44b8-9e40-40b640f24810
INFO:ecmwf.datastores.legacy_client:Request ID is 52878a9a-022d-44b8-9e40-40b640f24810
2026-07-30 05:06:28,887 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:06:50,519 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:07:02,081 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fb5d23be067d12e3ba44ed72e8340f22.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-01 04:00:00...

2026-07-30 05:07:07,052 INFO Request ID is 15e02df0-d8ef-406d-9e0f-a9b54e81a459
INFO:ecmwf.datastores.legacy_client:Request ID is 15e02df0-d8ef-406d-9e0f-a9b54e81a459
2026-07-30 05:07:07,347 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:07:57,732 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:08:23,506 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5ddb4d50d5b4c00e601262e0ec5bdd20.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-01 10:00:00...

2026-07-30 05:08:25,133 INFO Request ID is 3aef1a41-ae24-4379-a1ae-2b59da55cb80
INFO:ecmwf.datastores.legacy_client:Request ID is 3aef1a41-ae24-4379-a1ae-2b59da55cb80
2026-07-30 05:08:25,317 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:08:48,596 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5b8564c7026eaf04534cf72dfc1312d7.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-01 16:00:00...

2026-07-30 05:08:51,687 INFO Request ID is e5adbf80-bc79-4f06-9b57-a5b23c122179
INFO:ecmwf.datastores.legacy_client:Request ID is e5adbf80-bc79-4f06-9b57-a5b23c122179
2026-07-30 05:08:52,746 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:09:43,474 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

323bcd83fe7d271414aaabcc41fa46f6.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-01 22:00:00...

2026-07-30 05:09:45,200 INFO Request ID is 89100e62-2cab-4355-861a-d76624a9188c
INFO:ecmwf.datastores.legacy_client:Request ID is 89100e62-2cab-4355-861a-d76624a9188c
2026-07-30 05:09:45,508 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:10:10,259 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

dd8e0f02d5fce224f425704571966b0a.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-02 04:00:00...

2026-07-30 05:10:11,979 INFO Request ID is e297c92a-5fcb-4df1-81a8-9169e65707d2
INFO:ecmwf.datastores.legacy_client:Request ID is e297c92a-5fcb-4df1-81a8-9169e65707d2
2026-07-30 05:10:12,608 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:10:26,473 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

33d35803b663af24b3bba8a7348192a.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-02 10:00:00...

2026-07-30 05:10:28,085 INFO Request ID is c92fb8ec-1f66-463b-9f25-8275ca186443
INFO:ecmwf.datastores.legacy_client:Request ID is c92fb8ec-1f66-463b-9f25-8275ca186443
2026-07-30 05:10:28,217 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:10:45,916 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:11:06,204 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

614b274647bdbac0e8512fc417ab0ab3.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-02 16:00:00...

2026-07-30 05:11:09,919 INFO Request ID is 60cc0d77-a78d-4817-9a0b-bf92fb8fe796
INFO:ecmwf.datastores.legacy_client:Request ID is 60cc0d77-a78d-4817-9a0b-bf92fb8fe796
2026-07-30 05:11:10,064 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:11:26,175 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:11:33,906 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4fbb7c8b705cf0e44492b3d6e1ae7433.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-02 22:00:00...

2026-07-30 05:11:35,483 INFO Request ID is 9026490d-42a4-4e83-a747-eb754d439f47
INFO:ecmwf.datastores.legacy_client:Request ID is 9026490d-42a4-4e83-a747-eb754d439f47
2026-07-30 05:11:35,634 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:11:49,592 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:11:57,320 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

95c05fe3dee998f74976f71aa4699e45.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-03 04:00:00...

2026-07-30 05:11:59,008 INFO Request ID is 9003ee88-2824-48d0-bc74-db470767a4c4
INFO:ecmwf.datastores.legacy_client:Request ID is 9003ee88-2824-48d0-bc74-db470767a4c4
2026-07-30 05:11:59,141 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:12:12,992 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:12:20,733 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b19f85772884140768640ff12f9d14ff.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-03 10:00:00...

2026-07-30 05:12:22,607 INFO Request ID is 784cc870-16df-43d6-a971-5ba003e9cff9
INFO:ecmwf.datastores.legacy_client:Request ID is 784cc870-16df-43d6-a971-5ba003e9cff9
2026-07-30 05:12:22,738 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:12:56,581 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:13:13,847 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

de60e7a62fe81b9439f9488851bf21fa.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-03 16:00:00...

2026-07-30 05:13:15,757 INFO Request ID is 5566a786-66bd-4305-8edd-410ff054fdc4
INFO:ecmwf.datastores.legacy_client:Request ID is 5566a786-66bd-4305-8edd-410ff054fdc4
2026-07-30 05:13:15,888 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:13:50,764 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:14:07,985 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

96f3cf0961963aa9c527d00b96b043a6.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 253 at 2022-04-03 22:00:00...

2026-07-30 05:14:09,610 INFO Request ID is f0bdadd0-091a-4146-8c5c-3b4cfd044ffb
INFO:ecmwf.datastores.legacy_client:Request ID is f0bdadd0-091a-4146-8c5c-3b4cfd044ffb
2026-07-30 05:14:09,754 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:14:31,525 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:14:43,065 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2b442f36d3fb545b5252f1bb3b271638.grib:   0%|          | 0.00/2.95k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-09 08:00:00...

2026-07-30 05:14:47,130 INFO Request ID is 3d4843ec-a6e9-4c4a-a44b-2c75fcac33fe
INFO:ecmwf.datastores.legacy_client:Request ID is 3d4843ec-a6e9-4c4a-a44b-2c75fcac33fe
2026-07-30 05:14:47,288 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:15:24,007 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

16aa1baf492ad24e90484e3ff4faaf53.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-09 14:00:00...

2026-07-30 05:15:26,261 INFO Request ID is 1dd6c9ca-0204-4d87-9bae-51d484b39b0b
INFO:ecmwf.datastores.legacy_client:Request ID is 1dd6c9ca-0204-4d87-9bae-51d484b39b0b
2026-07-30 05:15:27,474 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:15:50,248 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:16:01,790 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

838a64bc44040b5b4901d9df7758f2b.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-09 20:00:00...

2026-07-30 05:16:03,548 INFO Request ID is fbf11556-5c37-4986-9639-c474769b85c4
INFO:ecmwf.datastores.legacy_client:Request ID is fbf11556-5c37-4986-9639-c474769b85c4
2026-07-30 05:16:03,695 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:16:25,546 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:16:37,093 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

14ceb35e2fb47bdfc118178c9fe6337e.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-10 02:00:00...

2026-07-30 05:16:38,968 INFO Request ID is 861b3d02-5eab-4b17-a805-17a8beff5aa3
INFO:ecmwf.datastores.legacy_client:Request ID is 861b3d02-5eab-4b17-a805-17a8beff5aa3
2026-07-30 05:16:39,131 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:17:01,503 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:18:34,702 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9564f949ea8dbfd603494f85ba990761.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-10 08:00:00...

2026-07-30 05:18:36,550 INFO Request ID is ed8a0b68-f88b-4bfc-8a51-1de7364a0275
INFO:ecmwf.datastores.legacy_client:Request ID is ed8a0b68-f88b-4bfc-8a51-1de7364a0275
2026-07-30 05:18:36,717 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:18:50,874 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:19:27,753 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e6491d9f04f9de3c0b347d61ea00b2e6.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-10 14:00:00...

2026-07-30 05:19:32,877 INFO Request ID is 68d40ee2-37bb-453a-81c5-6efa38fd6aad
INFO:ecmwf.datastores.legacy_client:Request ID is 68d40ee2-37bb-453a-81c5-6efa38fd6aad
2026-07-30 05:19:33,011 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:19:46,920 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:19:54,884 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2e16a0fd69686fee93445f91f8329d2f.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-10 20:00:00...

2026-07-30 05:19:56,343 INFO Request ID is 01b065af-dccf-444d-9cd5-3de32eb9f066
INFO:ecmwf.datastores.legacy_client:Request ID is 01b065af-dccf-444d-9cd5-3de32eb9f066
2026-07-30 05:19:56,471 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:20:10,367 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:20:18,115 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7581ef8bbd680761e0c4325ffb8589ef.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-11 02:00:00...

2026-07-30 05:20:20,854 INFO Request ID is c685d7f7-107f-4a21-92af-14e7d4e0d57f
INFO:ecmwf.datastores.legacy_client:Request ID is c685d7f7-107f-4a21-92af-14e7d4e0d57f
2026-07-30 05:20:20,986 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:20:54,113 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5dbfdbbe33cb727cb4947caabee8c8fe.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-11 08:00:00...

2026-07-30 05:20:56,661 INFO Request ID is 68d9b189-9f0f-4948-a94d-0cafdb58b010
INFO:ecmwf.datastores.legacy_client:Request ID is 68d9b189-9f0f-4948-a94d-0cafdb58b010
2026-07-30 05:20:56,814 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:21:18,515 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

58d01461858838cf34c3234975d5595d.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-11 14:00:00...

2026-07-30 05:21:20,110 INFO Request ID is 96070aaa-6f84-4d19-b550-1bf2bb4ce59a
INFO:ecmwf.datastores.legacy_client:Request ID is 96070aaa-6f84-4d19-b550-1bf2bb4ce59a
2026-07-30 05:21:20,253 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:21:42,050 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5340af7ce7f3fdc902ebbcbcda6f48da.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-11 20:00:00...

2026-07-30 05:21:43,717 INFO Request ID is c2ee0a47-e1e3-4aee-a06e-bb4b5d678063
INFO:ecmwf.datastores.legacy_client:Request ID is c2ee0a47-e1e3-4aee-a06e-bb4b5d678063
2026-07-30 05:21:43,856 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:22:05,670 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:22:17,785 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

915b6a2f02f420c8de1e68689b7d85de.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-12 02:00:00...

2026-07-30 05:22:19,614 INFO Request ID is 4a110ca7-ca98-43ad-b126-b97aea6b8e6c
INFO:ecmwf.datastores.legacy_client:Request ID is 4a110ca7-ca98-43ad-b126-b97aea6b8e6c
2026-07-30 05:22:19,798 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:22:41,476 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:22:53,018 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1be200e9e349a1565068fbeaf324541a.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-12 08:00:00...

2026-07-30 05:22:54,660 INFO Request ID is 83e5dfcc-b832-4791-b540-085fb73179a6
INFO:ecmwf.datastores.legacy_client:Request ID is 83e5dfcc-b832-4791-b540-085fb73179a6
2026-07-30 05:22:54,811 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:23:28,041 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:23:45,263 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

48dff1385394a573e193d184d492d012.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-12 14:00:00...

2026-07-30 05:23:47,541 INFO Request ID is 0b4e21c0-da98-4424-aac3-66f426f63fb9
INFO:ecmwf.datastores.legacy_client:Request ID is 0b4e21c0-da98-4424-aac3-66f426f63fb9
2026-07-30 05:23:49,265 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:24:12,115 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:24:23,649 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

791667552847216145dbbbe3c6a84d43.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-12 20:00:00...

2026-07-30 05:24:26,760 INFO Request ID is 7e1236e3-253a-47f1-9dbc-a2ec119f2cd8
INFO:ecmwf.datastores.legacy_client:Request ID is 7e1236e3-253a-47f1-9dbc-a2ec119f2cd8
2026-07-30 05:24:26,930 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:24:42,594 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:24:50,342 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a59864ee325fc61ab553dc9016b24aa1.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-13 02:00:00...

2026-07-30 05:24:51,862 INFO Request ID is cf35f2a8-4778-44bc-b242-8411a85eba6f
INFO:ecmwf.datastores.legacy_client:Request ID is cf35f2a8-4778-44bc-b242-8411a85eba6f
2026-07-30 05:24:51,993 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:25:16,609 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:25:28,147 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

63bc17096bd01d3f82abeac5f05dd9bf.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-13 08:00:00...

2026-07-30 05:25:29,803 INFO Request ID is fd772ef9-ddb7-4ff6-90c3-0235be6ccb9b
INFO:ecmwf.datastores.legacy_client:Request ID is fd772ef9-ddb7-4ff6-90c3-0235be6ccb9b
2026-07-30 05:25:29,942 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:25:53,862 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:26:05,388 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5c8344794065333cb7a6863d6cc6e2c5.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-13 14:00:00...

2026-07-30 05:26:07,549 INFO Request ID is b57de61d-c7b3-4670-acdc-812873cc7956
INFO:ecmwf.datastores.legacy_client:Request ID is b57de61d-c7b3-4670-acdc-812873cc7956
2026-07-30 05:26:08,643 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:26:31,194 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e207114b494ab962707d0d4481e83a29.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-13 20:00:00...

2026-07-30 05:26:32,836 INFO Request ID is 5de25635-c78e-436a-9922-12af7e4da481
INFO:ecmwf.datastores.legacy_client:Request ID is 5de25635-c78e-436a-9922-12af7e4da481
2026-07-30 05:26:33,764 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:26:57,166 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:27:08,713 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2b8bbc19c2bc791d5d7477b6c4b9b3b4.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-14 02:00:00...

2026-07-30 05:27:10,390 INFO Request ID is 037f9ed1-33b2-4986-bb52-6552269726af
INFO:ecmwf.datastores.legacy_client:Request ID is 037f9ed1-33b2-4986-bb52-6552269726af
2026-07-30 05:27:12,005 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:27:33,593 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:27:45,120 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5f7cd1d798a1a8d2fc4b0a4f8027029e.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-14 08:00:00...

2026-07-30 05:27:46,769 INFO Request ID is e08ab1b1-68df-4751-bf51-4513df98f8ab
INFO:ecmwf.datastores.legacy_client:Request ID is e08ab1b1-68df-4751-bf51-4513df98f8ab
2026-07-30 05:27:46,929 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:28:20,075 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4c74650ef08d38df37ab715bbf0a6c1c.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-14 14:00:00...

2026-07-30 05:28:23,138 INFO Request ID is 614a1889-a7a3-4049-bb9e-e18a1c276882
INFO:ecmwf.datastores.legacy_client:Request ID is 614a1889-a7a3-4049-bb9e-e18a1c276882
2026-07-30 05:28:23,275 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:28:48,228 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:28:59,770 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f9913aa83475d74d09d6799c1d0dda39.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 258 at 2022-06-14 20:00:00...

2026-07-30 05:29:01,437 INFO Request ID is 694c5d2d-e0da-4133-b2a8-49bc05cd3ce2
INFO:ecmwf.datastores.legacy_client:Request ID is 694c5d2d-e0da-4133-b2a8-49bc05cd3ce2
2026-07-30 05:29:01,597 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:29:23,631 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:29:35,671 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1653e1e6b72763ec5af13eeb3820669b.grib:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-08 08:00:00...

2026-07-30 05:29:37,545 INFO Request ID is 8f1e1340-a6e5-40f6-a5c7-a08f3fb238a0
INFO:ecmwf.datastores.legacy_client:Request ID is 8f1e1340-a6e5-40f6-a5c7-a08f3fb238a0
2026-07-30 05:29:38,738 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:30:01,250 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:30:12,790 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

81fa09efc2c009daa820530500ee7b06.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-08 14:00:00...

2026-07-30 05:30:14,508 INFO Request ID is 5b71a09d-7537-4fdf-b3ae-17346219d9df
INFO:ecmwf.datastores.legacy_client:Request ID is 5b71a09d-7537-4fdf-b3ae-17346219d9df
2026-07-30 05:30:14,654 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:30:47,813 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e9f10b9cad09eef839a808b600657b51.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-08 20:00:00...

2026-07-30 05:30:49,827 INFO Request ID is 98e53a74-d548-47e8-8e5a-b953b0bd13bc
INFO:ecmwf.datastores.legacy_client:Request ID is 98e53a74-d548-47e8-8e5a-b953b0bd13bc
2026-07-30 05:30:49,977 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:31:06,095 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:31:13,830 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

25facfaaf2563dacfcb59f6ec65b4a75.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-09 02:00:00...

2026-07-30 05:31:15,569 INFO Request ID is 8e405681-16c7-4abd-8b70-ee415ddd6e91
INFO:ecmwf.datastores.legacy_client:Request ID is 8e405681-16c7-4abd-8b70-ee415ddd6e91
2026-07-30 05:31:15,699 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:31:49,480 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

21244f2c93e0f1e2c25b3753f2ccef5c.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-09 08:00:00...

2026-07-30 05:31:51,193 INFO Request ID is 3c3c6f7f-d6b8-42a4-8117-7ad9eea1bdf9
INFO:ecmwf.datastores.legacy_client:Request ID is 3c3c6f7f-d6b8-42a4-8117-7ad9eea1bdf9
2026-07-30 05:31:51,335 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:32:05,258 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:32:12,985 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

c7f52961360a48ef78cbffc6a56d20b6.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-09 14:00:00...

2026-07-30 05:32:14,502 INFO Request ID is 5a192e4c-13f6-4a1f-8a73-4e42f1abd24b
INFO:ecmwf.datastores.legacy_client:Request ID is 5a192e4c-13f6-4a1f-8a73-4e42f1abd24b
2026-07-30 05:32:14,655 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:32:36,275 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e99128ba1bd70cbd5146d59d7a4d368d.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-09 20:00:00...

2026-07-30 05:32:39,038 INFO Request ID is 0ca0d198-9ae6-44b4-a9e0-61ab74aa7fa8
INFO:ecmwf.datastores.legacy_client:Request ID is 0ca0d198-9ae6-44b4-a9e0-61ab74aa7fa8
2026-07-30 05:32:39,173 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:33:00,743 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

44c090b9edccb835f7b478950153980a.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-10 02:00:00...

2026-07-30 05:33:02,614 INFO Request ID is d632faec-5d85-4661-be3c-23a92c60cb9b
INFO:ecmwf.datastores.legacy_client:Request ID is d632faec-5d85-4661-be3c-23a92c60cb9b
2026-07-30 05:33:02,764 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:33:18,440 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:33:26,199 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

11b4a5aa10bf85e002be2ae7c32578e7.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-10 08:00:00...

2026-07-30 05:33:27,902 INFO Request ID is 8929ee96-2938-4ba4-b734-d1c883ac8049
INFO:ecmwf.datastores.legacy_client:Request ID is 8929ee96-2938-4ba4-b734-d1c883ac8049
2026-07-30 05:33:28,246 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:33:42,840 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:33:51,589 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fa2984170b802c1536d69cf7552065fb.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-10 14:00:00...

2026-07-30 05:33:53,275 INFO Request ID is ba41ba3b-037c-48c4-9d50-0f76c66e6819
INFO:ecmwf.datastores.legacy_client:Request ID is ba41ba3b-037c-48c4-9d50-0f76c66e6819
2026-07-30 05:33:53,406 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:34:08,560 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8342635cbc8042e69467450b3f1e6885.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-10 20:00:00...

2026-07-30 05:34:10,151 INFO Request ID is 11cc8a76-ec0e-40d5-af3b-62e252a4e57e
INFO:ecmwf.datastores.legacy_client:Request ID is 11cc8a76-ec0e-40d5-af3b-62e252a4e57e
2026-07-30 05:34:10,282 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:34:31,960 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b1773cfe4ae55433420240c565d8accb.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-11 02:00:00...

2026-07-30 05:34:33,558 INFO Request ID is 37a093b6-042a-4527-8d29-dc7c963d9fc6
INFO:ecmwf.datastores.legacy_client:Request ID is 37a093b6-042a-4527-8d29-dc7c963d9fc6
2026-07-30 05:34:34,449 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:34:57,348 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7be5935587660aaf56203034c5c0b4bc.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-11 08:00:00...

2026-07-30 05:34:59,140 INFO Request ID is 13e8b996-6f48-49d0-9658-372a850fb3be
INFO:ecmwf.datastores.legacy_client:Request ID is 13e8b996-6f48-49d0-9658-372a850fb3be
2026-07-30 05:34:59,284 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:35:20,964 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5af70f3d794bd8992ca45215584e07a5.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-11 14:00:00...

2026-07-30 05:35:22,465 INFO Request ID is de3ab098-24f2-4b46-8836-8feffbb60548
INFO:ecmwf.datastores.legacy_client:Request ID is de3ab098-24f2-4b46-8836-8feffbb60548
2026-07-30 05:35:22,597 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:35:55,720 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

1e186cf79208efc4273e60808284b0f2.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-11 20:00:00...

2026-07-30 05:35:57,952 INFO Request ID is 213359d8-34e2-4281-b523-519628334db3
INFO:ecmwf.datastores.legacy_client:Request ID is 213359d8-34e2-4281-b523-519628334db3
2026-07-30 05:35:58,109 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:36:20,045 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

323def711a0dba70c6b12f7bad367fe8.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-12 02:00:00...

2026-07-30 05:36:22,138 INFO Request ID is e685a506-fdf2-4479-9f68-344a62920006
INFO:ecmwf.datastores.legacy_client:Request ID is e685a506-fdf2-4479-9f68-344a62920006
2026-07-30 05:36:22,554 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:36:44,150 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

528f674ab68cb49285103d0b2803a93f.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-12 08:00:00...

2026-07-30 05:36:45,807 INFO Request ID is 0628d1e4-a71d-4549-8070-30a4a98f5ccc
INFO:ecmwf.datastores.legacy_client:Request ID is 0628d1e4-a71d-4549-8070-30a4a98f5ccc
2026-07-30 05:36:45,942 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:37:02,009 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:37:13,012 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

325d20dbcd4feaed0770cf77c32fc050.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-12 14:00:00...

2026-07-30 05:37:15,636 INFO Request ID is aa2885ff-3db7-4b8e-8dde-8729b9e73756
INFO:ecmwf.datastores.legacy_client:Request ID is aa2885ff-3db7-4b8e-8dde-8729b9e73756
2026-07-30 05:37:15,773 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:37:37,395 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:37:48,934 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b688e635500d2265693d488aa24c9c67.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-12 20:00:00...

2026-07-30 05:37:53,013 INFO Request ID is 3b6d019d-55ef-4bca-8177-d328fd1efa74
INFO:ecmwf.datastores.legacy_client:Request ID is 3b6d019d-55ef-4bca-8177-d328fd1efa74
2026-07-30 05:37:53,162 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:38:15,693 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:38:27,237 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5786f998ecdfcf9ea41a2cf65c932f3f.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-13 02:00:00...

2026-07-30 05:38:28,975 INFO Request ID is 3682047b-052c-40dc-b390-cc4c3a090b2e
INFO:ecmwf.datastores.legacy_client:Request ID is 3682047b-052c-40dc-b390-cc4c3a090b2e
2026-07-30 05:38:29,107 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:38:50,787 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:39:02,312 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5fa0513694fb88ca545ad13f07b21c96.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-13 08:00:00...

2026-07-30 05:39:04,091 INFO Request ID is f5376fed-95a5-42ea-ba77-46ac1e1f535c
INFO:ecmwf.datastores.legacy_client:Request ID is f5376fed-95a5-42ea-ba77-46ac1e1f535c
2026-07-30 05:39:04,247 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:39:37,841 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7c8223f4f511b3fa62c41cefec9bb7.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-13 14:00:00...

2026-07-30 05:39:39,632 INFO Request ID is b7a5bb6a-06b8-436c-89c7-fb022bacd3d0
INFO:ecmwf.datastores.legacy_client:Request ID is b7a5bb6a-06b8-436c-89c7-fb022bacd3d0
2026-07-30 05:39:39,792 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:39:54,252 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:40:01,977 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

6891a213fcb550d3eb64bccbe3032e52.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-13 20:00:00...

2026-07-30 05:40:04,278 INFO Request ID is 3e2d08ac-5811-4f4d-af18-ae07cec9dbf5
INFO:ecmwf.datastores.legacy_client:Request ID is 3e2d08ac-5811-4f4d-af18-ae07cec9dbf5
2026-07-30 05:40:04,434 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:40:26,621 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fea2c53f7e54a01c49070dd85c4d731f.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

[LOG] Downloading PL data for ID 260 at 2022-06-14 02:00:00...

2026-07-30 05:40:28,732 INFO Request ID is 8c4c9847-50d6-42c2-8134-90d29e2be70b
INFO:ecmwf.datastores.legacy_client:Request ID is 8c4c9847-50d6-42c2-8134-90d29e2be70b
2026-07-30 05:40:28,887 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-07-30 05:40:50,526 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-07-30 05:41:02,064 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

38c7944bcd1b86ddb4d2984f92fbe88c.grib:   0%|          | 0.00/4.45k [00:00<?, ?B/s]

Extraction complete for 225 rows.

In [ ]:
# --- MERGE AND CLEAN ---
# Merge using 'time' (the original timestamp column in the input CSV)
merged_df = pd.merge(
    df_input,
    df_era5_new,
    on=['pyroCb_id', 'time', 'pixel_latitude', 'pixel_longitude'],
    how='left'
)

# Remove duplicate inputs if any exist based on the core unique identifiers
initial_count = len(merged_df)
merged_df = merged_df.drop_duplicates(subset=['pyroCb_id', 'time'])
final_count = len(merged_df)

print(f"Merged data. Removed {initial_count - final_count} duplicates.")

# Save result
merged_df.to_csv(FINAL_MERGED_CSV, index=False)
print(f"Final file saved to: {FINAL_MERGED_CSV}")
display(merged_df.head())

Merged data. Removed 0 duplicates.
Final file saved to: /content/drive/MyDrive/Pyrocb_data/merged_with_era5_pressure_final.csv

,pyroCb_id,time,pixel_latitude,pixel_longitude,latitude_vegetation,longitude_vegetation,cvh,cvl,tvh,tvl,...,slope,aspect_sin,aspect_cos,tpi,tri,rh_650,rh_750,rh_850,u_250,v_250
0,179,5/27/2021 6:00,33.287442,-108.588483,33.25,-108.5,0.888824,0.093579,3,16,...,29.0,0.374607,0.927184,4.567567,1.0,21.704834,13.238544,16.766167,30.144974,18.562988
1,179,5/27/2021 12:00,33.287442,-108.588483,33.25,-108.5,0.888824,0.093579,3,16,...,29.0,0.374607,0.927184,4.567567,1.0,27.561798,16.804243,29.028404,31.931488,23.416809
2,179,5/27/2021 18:00,33.287442,-108.588483,33.25,-108.5,0.888824,0.093579,3,16,...,29.0,0.374607,0.927184,4.567567,1.0,27.393448,14.195095,11.276022,31.079453,21.675842
3,179,5/28/2021 0:00,33.287442,-108.588483,33.25,-108.5,0.888824,0.093579,3,16,...,29.0,0.374607,0.927184,4.567567,1.0,22.148581,12.047037,10.058139,21.766632,8.594025
4,179,5/28/2021 6:00,33.287442,-108.588483,33.25,-108.5,0.888824,0.093579,3,16,...,29.0,0.374607,0.927184,4.567567,1.0,15.003980,13.651347,16.103186,23.590179,-3.886917